language: node_js

node_js:
  - "5.1"

before_install:
  - npm install -g gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp run-tests

addons:
  browserstack:
    username:
      secure: "JzUfrZKE8iIuutyiz1AMoQHe1hCgj4nq0CXWHTAoPCUbEZ0duXYt8NbOpQtkDT91C0TnCUoiMeLHJioyiA4EQm6PWTNBp/tzoD5i1vhGZ+iFhwS0eOMLx/OdGKOwddbWZVdcfRoUvv0TF5Wb15Q7goodstwVjnErNuZ0BMYdQnCEF9zduH3CJHa91LDWLWrrLz/oKUyQIwewcZ51bBs2EAnvt91mhOO2elvU6v5PtgKlS8IV7QTG2pXBLOIOHbbWr73lyse8E/lz41Gk3Tp8VG43pQ7syz+n+1rmnljlA1k3jEQPazJix1dxdfN6xIm/ur6k0mqWa1clRKTg2YVwItyXUIwsS2+fmOngow+NKzsYNtTwv7tSSD03VUZL2o1ydefEQBN9p8gk9rQdp+CMoR1LpzM8J1eIdRO419FpZyzPblDhJgfujC5O3h3Z/k4Cz+h+/8sx1Ms5rWN5/qJyTzQCFI6NK2MAgC1IO+nZmPJ/8sr6cJVltUBNqHbyuFE5bSnQdm/Ljpda2MMa8A+BCf5/qyATMHp/Gm5i7lyM/b3a2n1FRJQNjB2tRwSJpj5BJMr30F3Hz+6d+2/+lFHF2vMNF5S0WYbirl3nvu8JGf0s1YGoK67cYlSLsWmCp+PE2OwTTMS/EA30TOFKNs7XEnxwZAVd5Y2MjzUAOmiX25A="
    access_key:
      secure: "AIPRRo3KJLQy3jyDeOGHB3ywWxfzqQk3nIwfaGSnX/CRz8zWQK2WuCPa/r6Np2d2kyS1jg1kzNxpz3Q03umqKFwGpLLJqs6oMrL2SCzHMZwqzN1JKWSsVNonAOZLiOBozeVGKVEYq/7ge+Tum3fUqg/MEsHaZwmw0ZSgC9nXzipEWBpe+ftxnTwvsv8yhMl3eLYNVg8r5oQHAGug484SD1dRsXi5BUZrnF9GINdoQPQLUp6XcgYjsXHuWYBrMmpfoHTD/J+H5hWVB3IdmSeB2X6bJmuhhH9waJDjQYttflfc0FTJ/KTmqiFLOA2T+eh0dF9XnYKr46y6MaUhGcKo0VAC1Ej8WXR6n++PnS1SOHciSEnywvw0QP4MR3ip7we5YvTqLDeJInOpG1D6+FkC7cBZhEpZ15dgmqvEu8S7w8b8VXoHGa8g+qjvJUAcfVzZktNkApx5adTGlK2myR7qYRFjWdMgtS+EOQfLSMxdCGdoh2A3thgey9I+JLVXYWQqJeVU9XgQyYJzGkPSd9LiBifGQ1pJv3EI3YdjdTXTy59FLbNchzuLBopRH74qndzfrbRl2ypsP0lln2GJqgw+htMhlLgtkdv9QPaiBGNT5iDqP79/IK7cvqMVAeaq68UDCkIsoKtK0QvBIXzMw/iIxoIovzkj5pnW2eZuLJRPM0E="
